# .streamlit/secrets.toml

SUPABASE_URL = "https://jwuzkrrmbzglhigaabqj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3dXprcnJtYnpnbGhpZ2FhYnFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODUzMjUsImV4cCI6MjA3MjM2MTMyNX0.aH6eHn6QsNr-laZ4NCPLocm-quGAfPAnyuqSHi8CDiw"
